LineLength:
  Max: 100

Encoding:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

DoubleNegation:
  Enabled: false

StringLiterals:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/LambdaCall:
  Enabled: false

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "vendor/**/*"
