scss_files: 'app/assets/stylesheets/**/*.scss'
linters:
  SingleLinePerSelector:
    enabled: true
  Indentation:
    enabled: true
    character: space
    width: 2
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space
  EmptyLineBetweenBlocks:
    enabled: false
  SelectorFormat:
    enabled: false
  QualifyingElement:
    enabled: false
  NestingDepth:
    enabled: true
    max_depth: 5
  SelectorDepth:
    max_depth: 5
