scss_files: 'app/assets/stylesheets/**/*.scss'

exclude:
  - 'app/assets/stylesheets/app.scss'
  - 'app/assets/stylesheets/landing-page.scss'
  - 'app/assets/stylesheets/vendors/*'
  - 'vendor/*'

linters:
  SingleLinePerSelector:
    enabled: true
  Indentation:
    enabled: true
    character: space
    width: 2
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space
  EmptyLineBetweenBlocks:
    enabled: true
  SelectorFormat:
    enabled: false
  QualifyingElement:
    enabled: false
  NestingDepth:
    enabled: true
    max_depth: 6
  SelectorDepth:
    max_depth: 6
  PlaceholderInExtend:
    enabled: false
  NameFormat:
    enabled: false
