scss_files: 'app/assets/stylesheets/**/*.scss'

exclude: 'app/assets/stylesheets/modules/_action-sheet.scss', 'app/assets/stylesheets/modules/_loading.scss'

linters:
  SingleLinePerSelector:
    enabled: true
  Indentation:
    enabled: true
    character: space
    width: 2
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space
  EmptyLineBetweenBlocks:
    enabled: false
  SelectorFormat:
    enabled: false
  QualifyingElement:
    enabled: false
  NestingDepth:
    enabled: true
    max_depth: 6
  SelectorDepth:
    max_depth: 6
  PlaceholderInExtend:
    enabled: false
  NameFormat:
    enabled: false
  VendorPrefixes:
    enabled: false
