source 'https://rubygems.org'
source 'https://rails-assets.org'
ruby '2.2.0'

gem 'rails',                      '4.1.6'
gem 'unicorn',                    '4.7.0'
gem 'secure_headers',             '1.1.0'
gem 'jquery-rails',               '3.0.4'
gem 'slim-rails'
gem 'jbuilder',                   '2.1.3'
gem 'pg',                         '0.17.0'
gem 'sass-rails',                 '4.0.3'
gem 'coffee-rails',               '4.0.1'
gem 'uglifier',                   '2.5.3'
gem 'rack-canonical-host',        '0.0.8'
gem 'simple_form',                '3.0.2'
gem 'party_foul',                 '1.5.4'
gem 'devise',                     '3.2.2'
gem 'acts_as_votable',            '0.10.0'
gem 'rabl',                       '0.11.1'
gem 'oj',                         '2.10.3'
gem 'pusher',                     '0.14.1'
gem 'tod',                        '1.3.0'
gem 'recurrence',                 '1.2.0'
gem 'font-awesome-sass',          '4.0.3.1'
gem 'carrierwave',                '0.10.0'
gem 'apipie-rails',               '0.1.3'
gem 'cti',                        '0.1.1'
gem 'virtus',                     '1.0.3'
gem 'twilio-ruby',                '3.13.0'
gem 'foundation-rails',           '5.4.5.0'
gem 'roboto',                     '0.2.0'
gem 'newrelic_rpm',               '3.9.9.275'
gem 'link_thumbnailer',           '2.3.1'
gem 'acts-as-taggable-on',        '3.4.2'
gem 'elasticsearch-model',        '0.1.6'
gem 'elasticsearch-rails',        '0.1.6'
gem 'sidekiq',                    '3.3.0'
gem 'will_paginate',              '3.0.7'
gem 'roo',                        '1.13.2'
gem 'roadie-rails',               '1.0.3'
gem 'autoprefixer-rails',         '4.0.2.2'
gem 'devise-async',               '0.9.0'
gem 'intercom-rails',             '0.2.27'
gem 'active_model-errors_details','1.1.0'

gem 'rails-assets-angular',       '1.3.2'
gem 'rails-assets-angular-route', '1.3.2'
gem 'rails-assets-angular-resource', '1.3.2'
gem 'rails-assets-angularjs-rails-resource', '1.2.1'
gem 'rails-assets-angular--bower-angular-i18n', '1.3.11'
gem 'rails-assets-angular-messages', '1.3.2'
gem 'rails-assets-modernizr', '2.8.3'
gem 'rails-assets-jquery-maskedinput', '1.3.1'
gem 'rails-assets-angular-ui-sortable', '0.13.0'
gem 'rails-assets-arktisklada--jquery-ui-touch-punch', '0.2.3'
gem 'rails-assets-ng-file-upload',      '1.6.12'
gem 'rails-assets-ng-file-upload-shim', '1.6.12'
gem 'rails-assets-ng-tags-input',       '2.1.1'
gem 'rails-assets-mrodrigues--angular-elastic-input', '2.0.1'
gem 'rails-assets-angular-validation-match', '1.3.0'
gem 'rails-assets-mrodrigues--angular-input-masks', '1.3.1'
gem 'rails-assets-angular-foundation', '0.5.1'

group :production, :staging do
  gem 'rails_12factor',           '0.0.2'
  gem 'fog',                      '1.27.0'
end

gem 'database_cleaner',           '1.2.0',     require: false

group :development do
  gem 'pronto'
  gem 'pronto-rubocop'
  gem 'pronto-flay'
  gem 'rubocop',                  '0.26.1'
  gem 'foreman',                  '0.63.0'
  gem 'letter_opener',            '1.1.2'
  gem 'better_errors',            '2.0.0'
  gem 'binding_of_caller',        '0.7.2'
end

group :test do
  gem 'shoulda-matchers',         '2.7.0',     require: false
  gem 'simplecov',                '0.8.2',     require: false
  gem 'email_spec',               '1.5.0'
  gem 'faker',                    '1.4.3'
end

group :development, :test do
  gem 'rspec-rails',              '3.1.0'
  gem 'factory_girl_rails',       '4.3.0'
  gem 'pry-rails',                '0.3.2'
  gem 'dotenv-rails',             '0.9.0'
  gem 'vcr',                      '2.9.3'
  gem 'webmock',                  '1.19.0'
  gem 'timecop',                  '0.7.1'
  gem 'rspec_api_documentation',  '4.3.0'
end
