development:
  adapter: postgresql
  encoding: utf8
  database: dunno_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: dunno_test
  pool: 5
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: utf8
  database: dunno_production
  pool: 5
  min_messages: WARNING

beta:
  adapter: postgresql
  encoding: utf8
  database: dunno_beta
  pool: 5
  min_messages: WARNING
