v1:
  courses:
    schemes:
      - "#ffe681"
      - "#74c9f1"
      - "#b6a6f3"
      - "#ff8d68"
      - "#dd8c71"
      - "#cc81d8"
      - "#9fdb4c"
      - "#fb7272"
      - "#dbcd95"
      - "#98dedc"
      - "#7ce291"
      - "#d6bede"
