json.root_path(dashboard_teacher_path)
json.(@resource, :id, :name, :phone_number, :email, :authentication_token, :completed_tutorial)
json.profile(@resource.profile_name)
json.courses_count(@resource.profile.courses.count)
json.students_count(@resource.profile.courses.flat_map(&:students).count)
json.notifications_count(@resource.profile.courses.flat_map(&:notifications).count)
